/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoRouteImport } from './routes/Memo'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as UseereffRouteImport } from './routes/useereff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoRoute = MemoRouteImport.update({
  id: '/Memo',
  path: '/Memo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UseereffRoute = UseereffRouteImport.update({
  id: '/useereff',
  path: '/useereff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Memo': typeof MemoRoute
  '/profile': typeof ProfileRoute
  '/useereff': typeof UseereffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Memo': typeof MemoRoute
  '/profile': typeof ProfileRoute
  '/useereff': typeof UseereffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Memo': typeof MemoRoute
  '/profile': typeof ProfileRoute
  '/useereff': typeof UseereffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Memo' | '/profile' | '/useereff'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Memo' | '/profile' | '/useereff'
  id: '__root__' | '/' | '/Memo' | '/profile' | '/useereff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoRoute: typeof MemoRoute
  ProfileRoute: typeof ProfileRoute
  UseereffRoute: typeof UseereffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Memo': {
      id: '/Memo'
      path: '/Memo'
      fullPath: '/Memo'
      preLoaderRoute: typeof MemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useereff': {
      id: '/useereff'
      path: '/useereff'
      fullPath: '/useereff'
      preLoaderRoute: typeof UseereffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoRoute: MemoRoute,
  ProfileRoute: ProfileRoute,
  UseereffRoute: UseereffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
